import { CommonModule, DatePipe } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import {
  AArrowDown,
  AArrowUp,
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUp01,
  ArrowUpRight,
  BarChart2,
  Boxes,
  Building2,
  Calculator,
  ChartPie,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheckBig,
  ClipboardPen,
  Clock,
  Compass,
  Computer,
  ContactRound,
  Crosshair,
  Delete,
  Droplet,
  Droplets,
  Edit3,
  Eye,
  File,
  FileDown,
  FilePenLine,
  FileText,
  Filter,
  Gauge,
  GitGraph,
  Globe,
  History,
  Hourglass,
  Inbox,
  Info,
  Layers,
  Layers2,
  LayoutDashboard,
  List,
  Loader2,
  Lock,
  LogOut,
  LucideAngularModule,
  Map,
  MapPin,
  MapPinPlus,
  Maximize,
  Maximize2,
  Minus,
  MinusCircle,
  NotebookPen,
  Package,
  PackageCheck,
  PackageMinus,
  Pen,
  Pencil,
  Plug,
  Plus,
  PlusCircle,
  PlusSquare,
  Power,
  Printer,
  PrinterCheck,
  RefreshCw,
  Rotate3d,
  RotateCcw,
  Save,
  SaveAll,
  Scale,
  Search,
  SearchX,
  Share2,
  Sheet,
  Shuffle,
  Sliders,
  SquarePen,
  SquarePlus,
  Star,
  Sun,
  Target,
  TestTubeDiagonal,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  User,
  UserCheck,
  UserCog,
  UserRound,
  UsersRound,
  Wallet,
  Weight,
  X,
} from 'lucide-angular';
import { AdminComponent } from './admin.component';
import { AdminRoutes } from './admin.routing';
import { BottomNavComponent } from './components/bottom-nav/bottom-nav.component';
import { BottomSheetComponent } from './components/bottom-sheet/bottom-sheet.component';
import { FabButtonComponent } from './components/fab-button/fab-button.component';
import { LucideIconsComponent } from './components/lucide-icons.component';
import { SummaryCardComponent } from './components/summary-card/summary-card.component';
import { TransactionItemComponent } from './components/transaction-item/transaction-item.component';
import { AlokasiComponent } from './pages/alokasi/alokasi.component';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { LoginComponent } from './pages/login/login.component';
import { MonitoringComponent } from './pages/monitoring/monitoring.component';
import { PendapatanComponent } from './pages/pendapatan/pendapatan.component';
import { PengeluaranComponent } from './pages/pengeluaran/pengeluaran.component';
import { RupiahPipe } from './pipes/rupiah.pipe';

@NgModule({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [DatePipe],
  declarations: [
    AdminComponent,
    LucideIconsComponent,
    BottomNavComponent,
    SummaryCardComponent,
    DashboardComponent,
    TransactionItemComponent,
    PengeluaranComponent,
    FabButtonComponent,
    BottomSheetComponent,
    PendapatanComponent,
    MonitoringComponent,
    AlokasiComponent,
    LoginComponent,
  ],
  imports: [
    RouterModule.forChild(AdminRoutes),
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    CommonModule,
    RupiahPipe,

    LucideAngularModule.pick({
      AArrowUp,
      AArrowDown,
      UserCheck,
      Sheet,
      PrinterCheck,
      ArrowLeftRight,
      CircleCheckBig,
      Hourglass,
      Scale,
      Power,
      ContactRound,
      UsersRound,
      X,
      UserRound,
      AlertTriangle,
      Check,
      Lock,
      Eye,
      Info,
      UserCog,
      SquarePlus,
      Printer,
      RefreshCw,
      ChevronDown,
      ChevronUp,
      Inbox,
      SaveAll,
      Calculator,
      RotateCcw,
      Save,
      Droplets,
      Gauge,
      CheckCircle,
      Filter,
      File,
      SquarePen,
      Trash2,
      GitGraph,
      History,
      PackageMinus,
      TestTubeDiagonal,
      FilePenLine,
      PlusCircle,
      Pencil,
      ArrowLeft,
      FileDown,
      Clock,
      Sun,
      Search,
      Pen,
      Target,
      Activity,
      TrendingUp,
      AlertCircle,
      Weight,
      PackageCheck,
      MinusCircle,
      ChartPie,
      Plug,
      Plus,
      PlusSquare,
      ClipboardPen,
      FileText,
      Truck,
      Package,
      Rotate3d,
      List,
      ChevronLeft,
      Layers,
      ChevronRight,
      Maximize,
      Sliders,
      Edit3,
      Star,
      Layers2,
      Compass,
      Minus,
      MapPin,
      Map,
      Share2,
      Crosshair,
      Loader2,
      MapPinPlus,
      Maximize2,
      Shuffle,
      Computer,
      Globe,
      SearchX,
      ArrowUp01,
      Droplet,
      LogOut,
      NotebookPen,
      User,
      Building2,
      BarChart2,
      Boxes,
      LayoutDashboard,
      TrendingDown,

      ArrowUpRight,
      Wallet,
      Delete,
    }),
  ],
})
export class AdminModule {}
